version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_SERVER: admin
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
